### PR TITLE
initializeKelonio now creates an empty state

### PR DESCRIPTION
**Pull request by thomaschaplin**
This PR fixes https://github.com/mtkennerly/kelonio/issues/5 by changing the logic from throwing an error to logging a warning.

### CODE REVIEW

**Comment by thomaschaplin** [comment]
@mtkennerly this PR fixes the issue I raised earlier - https://github.com/mtkennerly/kelonio/issues/5

**Comment by mtkennerly** [comment]
Thanks for this! I think we could have a simpler solution, though. Let me know your thoughts - maybe I'm overlooking a case that this wouldn't handle as well:

```diff
diff --git a/src/reporters.ts b/src/reporters.ts
index 3b9c44f..ecd58d7 100644
--- a/src/reporters.ts
+++ b/src/reporters.ts
@@ -27,7 +27,7 @@ export class JestReporter implements jest.Reporter {
     }
     static initializeKelonio(): void {
         const state = new BenchmarkFileState();
-        state.delete();
+        state.write({});
         benchmark.events.on("record", (description, measurement) => {
             const b = new Benchmark();
             if (state.exists()) {
```

The error is complaining about the state file not existing, so this change would create a dummy state file during `initializeKelonio()`. That way, we avoid the error when the developer has correctly invoked `initializeKelonio()`, but still throw an error if it has been forgotten (whereas a warning is much easier to miss). The reporting code already handles the case when there are no results, so it would just print a blank line.

**Comment by thomaschaplin** [comment]
> Thanks for this! I think we could have a simpler solution, though. Let me know your thoughts - maybe I'm overlooking a case that this wouldn't handle as well:
> 
> ```diff
> diff --git a/src/reporters.ts b/src/reporters.ts
> index 3b9c44f..ecd58d7 100644
> --- a/src/reporters.ts
> +++ b/src/reporters.ts
> @@ -27,7 +27,7 @@ export class JestReporter implements jest.Reporter {
>      }
>      static initializeKelonio(): void {
>          const state = new BenchmarkFileState();
> -        state.delete();
> +        state.write({});
>          benchmark.events.on("record", (description, measurement) => {
>              const b = new Benchmark();
>              if (state.exists()) {
> ```
> 
> Since the error is complaining about the state file not existing, this change would create a dummy state file during `initializeKelonio()`. That way, we avoid the error when the developer has correctly invoked `initializeKelonio()`, but still throw an error if it has been forgotten (whereas a warning is much easier to miss). The reporting code already handles the case when there are no results, so it would just print a blank line.

I must admit, I wasn't happy with my solution but your solution is great and very simple, I've checked it against my "known" issues and it's working as expected. I've updated the unit tests to accommodate these changes.

**Comment by thomaschaplin** [comment]
@mtkennerly  I can't seem to request your review on this PR again, thanks for the advise on the change! Really looking forward to a new release with these changes (if you approve 🤞🏼)

**Review by mtkennerly — APPROVED** [review]
:+1:

**Comment by mtkennerly** [comment]
@thomaschaplin This is now available in [v0.5.0](https://github.com/mtkennerly/kelonio/releases/tag/v0.5.0) 🎉

**Pull request merged**
