### PR TITLE
test(jest): rename keepState to keepStateAtEnd

### PR DESCRIPTION
**Pull request by thomaschaplin**
To begin, I'd like to say thank you @mtkennerly for building this tool, it's a great piece of work!

This pull request implements the changes found in https://github.com/mtkennerly/kelonio/pull/1 but with the recommended naming changes from `keepState` to `keepStateAtEnd`. I made a new PR as I didn't have permission to edit the existing PR which has these changes.

### CODE REVIEW

**Comment by mtkennerly** [comment]
Thanks for the PR and the kind words :+1:

**Comment by thomaschaplin** [comment]
Thank you for merging this in @mtkennerly! Yes please, if you could create a new release I'd be very grateful 👍🏼

**Comment by thomaschaplin** [comment]
Hey @mtkennerly do you know when you might get round to releasing these changes? 🙏🏼

**Comment by mtkennerly** [comment]
Should be within the next 12 hours, after I'm done with work \:)

**Comment by mtkennerly** [comment]
v0.4.0 is now available with the changes from both of your PRs \:D

**Comment by thomaschaplin** [comment]
> v0.4.0 is now available with the changes from both of your PRs :D

Awesome, thank you so much!

**Pull request merged**
